-- Insert sample users
INSERT OR IGNORE INTO users (id, email, password, first_name, last_name, role, is_active, created_at, updated_at)
VALUES
  ('550e8400-e29b-41d4-a716-446655440000', 'admin@myaibo.in', '$2a$10$hashedpassword', 'Admin', 'User', 'admin', 1, datetime('now'), datetime('now')),
  ('550e8400-e29b-41d4-a716-446655440001', 'editor@myaibo.in', '$2a$10$hashedpassword', 'Content', 'Editor', 'editor', 1, datetime('now'), datetime('now'));

-- Insert sample blogs with simple content
INSERT OR IGNORE INTO blogs (id, title, slug, excerpt, content, author_id, status, published_at, categories, tags, meta_title, meta_description, view_count, created_at, updated_at)
VALUES
  ('550e8400-e29b-41d4-a716-446655440002', 'The Rise of Agentic AI', 'the-rise-of-agentic-ai', 'Exploring how agentic AI systems are revolutionizing automation and decision-making processes across industries.', '<h2>Introduction</h2><p>Agentic AI represents a paradigm shift in artificial intelligence, moving beyond reactive systems to proactive, goal-oriented intelligence that can act autonomously to achieve objectives.</p><h2>What is Agentic AI?</h2><p>Unlike traditional AI systems that respond to specific inputs, agentic AI can initiate actions without direct human intervention, learn from outcomes and adapt strategies, coordinate multiple tasks simultaneously, and make decisions in complex, dynamic environments.</p><h2>Applications Across Industries</h2><p>Agentic AI is transforming various sectors including healthcare, finance, and manufacturing.</p>', '550e8400-e29b-41d4-a716-446655440000', 'published', '2024-12-01 00:00:00', '["AI & ML", "Technology Trends"]', '["agentic-ai", "automation", "artificial-intelligence"]', 'The Rise of Agentic AI - MyAibo', 'Exploring how agentic AI systems are revolutionizing automation and decision-making processes across industries.', 150, datetime('now'), datetime('now')),
  ('550e8400-e29b-41d4-a716-446655440003', 'Machine Learning in 2025', 'machine-learning-in-2025', 'A comprehensive look at the emerging trends shaping the machine learning landscape in 2025 and beyond.', '<h2>The Evolving ML Landscape</h2><p>As we enter 2025, machine learning continues to evolve at a rapid pace, driven by advances in computational power, data availability, and algorithmic innovation.</p><h2>Key Trends for 2025</h2><p>Multimodal learning, edge AI and federated learning, explainable AI, and AI for scientific discovery are among the key trends shaping the future of machine learning.</p>', '550e8400-e29b-41d4-a716-446655440000', 'published', '2024-11-15 00:00:00', '["Machine Learning", "AI Trends"]', '["machine-learning", "2025-predictions", "ai-trends"]', 'Machine Learning in 2025: Trends and Predictions - MyAibo', 'A comprehensive look at the emerging trends shaping the machine learning landscape in 2025 and beyond.', 89, datetime('now'), datetime('now')),
  ('550e8400-e29b-41d4-a716-446655440004', 'AI Ethics and Governance', 'ai-ethics-and-governance', 'Understanding the importance of ethical AI development and the frameworks needed to ensure responsible deployment.', '<h2>The Imperative for Ethical AI</h2><p>As artificial intelligence becomes increasingly integrated into our daily lives and critical infrastructure, the need for ethical AI development and governance has never been more pressing.</p><h2>Core Ethical Principles</h2><p>Fairness and bias mitigation, transparency and explainability, privacy and data protection, and accountability are the core principles of ethical AI.</p>', '550e8400-e29b-41d4-a716-446655440001', 'published', '2024-10-20 00:00:00', '["AI Ethics", "Governance"]', '["ai-ethics", "responsible-ai", "governance"]', 'AI Ethics and Governance: Building Responsible AI Systems - MyAibo', 'Understanding the importance of ethical AI development and the frameworks needed to ensure responsible deployment.', 67, datetime('now'), datetime('now'));
